#!/bin/bash

# alias bpp='source ~/bin/bpp.sh !$'

MAX_HISTORY=1000
NUMBER_CHOICES=10

#pattern=$2
#pattern="'$*'"
pattern="$*"

fancy_history_grep () {
    history $MAX_HISTORY | grep "$pattern" | grep -v 'bpp ' | tail -n $NUMBER_CHOICES

    if true; then
	echo -n "Make your choice: "
	read choice
	if [[ "$choice" == "" || "$choice" -le 0 ]]
	then
	    echo "exiting"
	else
	    command=!$choice
	    FILENAME="/Users/cvonkrogh/bin/BPP_COMMAND_$choice"
	    rm -f $FILENAME
	    touch $FILENAME
	    echo "# generated by bpp.sh" >> $FILENAME
	    echo "set -o histexpand" >> $FILENAME
	    echo "set -o history" >> $FILENAME
	    echo "$command" >> $FILENAME
	    source $FILENAME
	    rm -f $FILENAME
	fi
    fi

    return
}

if [ "$pattern" == "" -o "$pattern" == '!$' ]
then
    echo ""
    echo "Usage:"
    echo "   $ bpp mvn c"
    echo "   $ bpp \"mvn \""
    echo ""
    # { printf "ls"; } | source /dev/stdin # this works !
    # { printf '!506'; } | source /dev/stdin # this does not work !
else
    pattern=${pattern:3}
    fancy_history_grep "$pattern"
fi
